---
- name: Configuring apache using child playbooks
  hosts: all
  tasks:
   - name: Call mutiple childplaybooks
     include: "{{item}}"
     with_items:
      - install.yml
      - edit_index.yml
      - restart.yml
      - check_url_response.yml
...
