---
- name: Install required s/w's
  hosts: all
  tasks:
   - name: Software installtions for ci-cd
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
      - {a: tomcat9,b: no}
      - {a: tomcat9-admin,b: no}
- name: Continuous Download and Continuous Build
  hosts: devserver
  tasks:
   - name: Download the development code from github
     git:
      repo: https://github.com/intelliqittrainings/maven.git
      dest: /home/ubuntu/mygit
   - name: Create an artifact from the above code
     shell: cd /home/ubuntu/mygit;mvn package
   - name: Fetch the artifact from Dev server to Controller
     fetch:
      src: /home/ubuntu/mygit/webapp/target/webapp.war
      dest: /tmp
- name: Continuous Deployment and Continuous Testing
  hosts: qaserver
  tasks:
   - name: Deploy the artifact into tomcat on qaserver
     copy:
      src: /tmp/172.31.17.35/home/ubuntu/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat9/webapps/testapp.war
   - name: Download the selenium scripts
     git:
      repo: https://github.com/intelliqittrainings/FunctionalTesting.git
      dest: /home/ubuntu/test-git
   - name: Run the selenium scripts
     shell: java -jar /home/ubuntu/test-git/testing.jar
- name: Continuous Delivery
  hosts: prodserver
  tasks:
   - name: Deploy artifact into tomcat on the prodserver
     copy:
      src: /tmp/172.31.17.35/home/ubuntu/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat9/webapps/prodaqpp.war
...








