---
- name: Implementing Handlers
  hosts: all
  tasks:
   - name: Install apache2
     apt:
      name: apache2
      state: present
     notify: Check url response
   - name: Edit the index.html file
     copy:
      content: "Welcome to IntelliQIt"
      dest: /var/www/html/index.html
     notify: Restart apache2
  handlers:
   - name: Restart apache2
     service:
      name: apache2
      state: restarted
   - name: Check url response
     uri:
      url: "{{item}}"
     with_items:
      - http://172.31.16.84
      - http://172.31.29.58


...

