---
- name: Install multiple s/w applications
  hosts: all
  tasks:
   - name: Install s/w's
     apt:
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - tree
      - maven
      - git
